import { subDays } from "date-fns";
import type { PinsData } from "@/lib/store";

const scoutId = "11111111-1111-4111-8111-111111111111";
const misoId = "22222222-2222-4222-8222-222222222222";
const now = () => new Date().toISOString();

export const DEFAULT_DATA: PinsData = {
  pets: [
    {
      id: scoutId,
      name: "Scout",
      species: "dog",
      breed: "Mixed",
      weightKg: 22,
      sex: "male",
      color: "#d97706",
      updatedAt: now(),
    },
    {
      id: misoId,
      name: "Miso",
      species: "cat",
      breed: "Domestic shorthair",
      weightKg: 4.2,
      sex: "female",
      color: "#64748b",
      updatedAt: now(),
    },
  ],
  activePetId: scoutId,
  logs: [
    {
      id: crypto.randomUUID(),
      petId: scoutId,
      medType: "insulin",
      siteId: "dog-side-scruff",
      compound: "Vetsulin",
      dose: 8,
      unit: "IU",
      timestamp: new Date().toISOString(),
      notes: "Morning insulin",
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      petId: scoutId,
      medType: "oral",
      compound: "Heartgard",
      dose: 1,
      unit: "chew",
      timestamp: subDays(new Date(), 2).toISOString(),
      updatedAt: subDays(new Date(), 2).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      petId: scoutId,
      medType: "injection",
      siteId: "dog-side-flank",
      compound: "Gabapentin",
      dose: 100,
      unit: "mg",
      timestamp: subDays(new Date(), 4).toISOString(),
      updatedAt: subDays(new Date(), 4).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      petId: misoId,
      medType: "topical",
      siteId: "cat-top-scruff",
      compound: "Revolution",
      dose: 1,
      unit: "pump",
      timestamp: subDays(new Date(), 6).toISOString(),
      notes: "Monthly flea / heartworm",
      updatedAt: subDays(new Date(), 6).toISOString(),
    },
  ],
  inventory: [
    {
      id: crypto.randomUUID(),
      name: "Vetsulin",
      form: "insulin",
      petId: scoutId,
      medType: "insulin",
      concentration: 40,
      totalVolume: 10,
      remainingVolume: 7.2,
      unit: "IU",
      color: "#3b82f6",
      frequency: "2x/day",
      defaultDose: 8,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Heartgard",
      form: "chew",
      petId: scoutId,
      medType: "oral",
      totalVolume: 6,
      remainingVolume: 4,
      unit: "chew",
      color: "#10b981",
      frequency: "Monthly",
      defaultDose: 1,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      name: "NexGard",
      form: "chew",
      petId: scoutId,
      medType: "oral",
      totalVolume: 6,
      remainingVolume: 5,
      unit: "chew",
      color: "#f59e0b",
      frequency: "Monthly",
      defaultDose: 1,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Revolution",
      form: "topical",
      petId: misoId,
      medType: "topical",
      totalVolume: 6,
      remainingVolume: 5,
      unit: "pump",
      color: "#8b5cf6",
      frequency: "Monthly",
      defaultDose: 1,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      name: "Gabapentin",
      form: "tablet",
      petId: null,
      medType: "oral",
      totalVolume: 30,
      remainingVolume: 22,
      unit: "tablet",
      color: "#ec4899",
      frequency: "As needed",
      defaultDose: 1,
      updatedAt: now(),
    },
  ],
  schedule: [
    {
      id: crypto.randomUUID(),
      petId: scoutId,
      compound: "Vetsulin",
      medType: "insulin",
      dose: 8,
      unit: "IU",
      time: "08:00",
      days: [0, 1, 2, 3, 4, 5, 6],
      active: true,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      petId: scoutId,
      compound: "Vetsulin",
      medType: "insulin",
      dose: 8,
      unit: "IU",
      time: "20:00",
      days: [0, 1, 2, 3, 4, 5, 6],
      active: true,
      updatedAt: now(),
    },
    {
      id: crypto.randomUUID(),
      petId: misoId,
      compound: "Revolution",
      medType: "topical",
      dose: 1,
      unit: "pump",
      time: "09:00",
      days: [1],
      active: true,
      updatedAt: now(),
    },
  ],
};
